import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'

import 'react-loading-skeleton/dist/skeleton.css'

const inter = Noto_Sans({ weight: "500", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <Providers>
        <body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  )
}
